version: '3.8'

services:
  btcpayserver:
    image: btcpayserver/btcpayserver:${BTCPAY_VERSION}
    restart: always
    ports:
      - "${BTCPAY_PORT}:${BTCPAY_PORT}"
    environment:
      BTCPAY_HOST: "${BTCPAY_HOST}"
      BTCPAY_PORT: "${BTCPAY_PORT}"
      BTCPAY_BIND: "${BTCPAY_BIND}"
      BTCPAY_NETWORK: "${BTCPAY_NETWORK}"
      BTCPAY_BTCEXPLORERURL: "${BTCPAY_BTCEXPLORERURL}"
      BTCPAY_POSTGRES: "${BTCPAY_POSTGRES}"
    depends_on:
      - nbxplorer
      - postgres
    volumes:
      - btcpay_data:/data

  nbxplorer:
    image: nicolasdorier/nbxplorer:${NBXPLORER_VERSION}
    restart: always
    environment:
      NBXPLORER_NETWORK: "${NBXPLORER_NETWORK}"
      NBXPLORER_BTCRPCURL: "${NBXPLORER_BTCRPCURL}"
      NBXPLORER_BTCRPCUSER: "${NBXPLORER_BTCRPCUSER}"
      NBXPLORER_BTCRPCPASSWORD: "${NBXPLORER_BTCRPCPASSWORD}"
      NBXPLORER_BTCNODEENDPOINT: "${NBXPLORER_BTCNODEENDPOINT}"
      NBXPLORER_CHAINS: "${NBXPLORER_CHAINS}"
      NBXPLORER_BIND: "${NBXPLORER_BIND}"
      NBXPLORER_ELECTRUM: "${NBXPLORER_ELECTRUM}"
      NBXPLORER_DB_HOST: "${NBXPLORER_DB_HOST}"
      NBXPLORER_DB_PORT: "${NBXPLORER_DB_PORT}"
      NBXPLORER_DB_USER: "${NBXPLORER_DB_USER}"
      NBXPLORER_DB_PASSWORD: "${NBXPLORER_DB_PASSWORD}"
      NBXPLORER_DB_NAME: "${NBXPLORER_DB_NAME}"
      NBXPLORER_POSTGRES: "${NBXPLORER_POSTGRES}"
      NBXPLORER_NOAUTH: "${NBXPLORER_NOAUTH}"
    depends_on:
      - postgres
    volumes:
      - nbxplorer_data:/data
    ports:
      - "${NBXPLORER_PORT}:${NBXPLORER_PORT}"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}"

volumes:
  btcpay_data:
  postgres_data:
  nbxplorer_data:
